#ifndef COMMAND_AND_DOMINATE_SRC_IMAGE_IMAGE2D_FORWARD_H_
#define COMMAND_AND_DOMINATE_SRC_IMAGE_IMAGE2D_FORWARD_H_

#include <memory>

class Image2D;
using Image2DPtr = std::shared_ptr<Image2D>;

#endif // !COMMAND_AND_DOMINATE_SRC_IMAGE_IMAGE2D_FORWARD_H_
