#ifndef COMMAND_AND_DOMINATE_SRC_WINDOW_KEY_TYPE_FORWARD_H_
#define COMMAND_AND_DOMINATE_SRC_WINDOW_KEY_TYPE_FORWARD_H_

enum class KeyType : int;

#endif // !COMMAND_AND_DOMINATE_SRC_WINDOW_KEY_TYPE_FORWARD_H_
